remote_theme: pages-themes/minimal@v0.2.0
title: Stillman Research Day 2026
description: An opportunity to share and discuss research from the Stillman School of Business faculty at Seton Hall University.
